server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/user/**
          - id: event-service
            uri: lb://event-service
            predicates:
              - Path=/event/**